[package]
name = "emch-rs"
version = "0.0.0"
edition = "2021"
description = "Embedded search implemented in Rust"
license = "MIT"
repository = "https://github.com/AsherJingkongChen/emch.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/web/lib.rs"
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.64"

[dependencies.wasm-bindgen]
version = "0.2.87"
default-features = false

[dependencies.ndarray]
version = "0.15.6"
default-features = false

[dependencies.tokenizers]
version = "0.13.4"
default-features = false
features = ["unstable_wasm"]
