[package]
name = "emch-wasm"
version = "0.0.0"
edition = "2021"
description = "Chat with embeddings locally in Web Assembly"
license = "MIT"
repository = "https://github.com/AsherJingkongChen/emch.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "emch"
path = "src/emch.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.87" }
js-sys = { version = "0.3.64" }
ndarray = { version = "0.15.6" }

[dependencies.getrandom]
version = "0.2.10"
features = ["js"]

[dependencies.tokenizers]
version = "0.13.4"
default-features = false
features = ["unstable_wasm"]
