[package]
name = "emch-wasm"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "core"
path = "src/core.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.87" }
js-sys = { version = "0.3.64" }

[dependencies.getrandom]
version = "0.2.10"
features = ["js"]

[dependencies.tokenizers]
version = "0.13.4"
default-features = false
features = ["unstable_wasm"]
